application: transfiguration-catalog
version: 1
runtime: python27
api_version: 1
threadsafe: true
inbound_services:
- warmup

skip_files:
- ^(.*/)?.*\.pyc

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /images
  static_dir: catalog/static/images
  expiration: 14d
- url: /css
  static_dir: catalog/static/css
  expiration: 7d
- url: /js
  static_dir: catalog/static/js
  expiration: 7d
- url: /fonts
  static_dir: catalog/static/fonts
  expiration: 7d
- url: /.*
  script: catalog.views.application
