application: transfiguration-catalog
version: 1
runtime: python27
api_version: 1
threadsafe: false

skip_files:
- ^(.*/)?.*\.pyc

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  expiration: 30d
- url: /images
  static_dir: static/images
  expiration: 14d
- url: /css
  static_dir: static/css
  expiration: 7d
- url: /js
  static_dir: static/js
  expiration: 7d
- url: /fonts
  static_dir: static/fonts
  expiration: 7d
- url: /borrow
  script: catalog.views.application
  login: required
- url: /return
  script: catalog.views.application
  login: required
- url: /.*
  script: catalog.views.application

env_variables:
  TZ: 'EST'
